spring:
    data:
      mongodb: mongodb://root:root@localhost:27017/customer?authSource=admin
mongodb:
  username: root
  password: root
  host: localhost
  port: 27017
  database: customer
  authentication-database: admin
server:
  port: 8083